name: Test

on:
  push:

  schedule:
  - cron: "0 12 * * 0"  # run once a week on Sunday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        os:
        - ubuntu-22.04
        - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache packages
        uses: actions/cache@v4
        id: cache
        with:
          path: .cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-testing-*.txt') }}
          restore-keys: |
            ${{ runner.os }}-test
      - name: Run black code style check
        if: ${{ matrix.python-version == '3.13' }}
        run: |
          pip install black
          black --check src setup.py
      - name: Run isort code style check
        if: ${{ matrix.python-version == '3.13' }}
        run: |
          pip install isort
          isort --check-only --df src setup.py
      - name: Install dependencies
        run: |
          pip install -U pip wheel
          pip install -r requirements-testing.txt
      - name: Run Tests
        run: |
          zope-testrunner --test-path=src
